#!/bin/bash

# $1 - bin
tmp=`mktemp -u`

pushd `dirname $1`
sftp pi@192.168.43.215 <<< $(printf "put `basename $1` $tmp\nquit")
ssh pi@192.168.43.215 "stm32flash -w $tmp -v /dev/ttyAMA0;rm -v $tmp"
popd
